# Generated by Django 6.0.3 on 2026-03-09 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('categorie', models.CharField(choices=[('electronique', 'Électronique'), ('vetements', 'Vêtements'), ('chaussures', 'Chaussures'), ('accessoires', 'Accessoires'), ('maison', 'Maison'), ('beaute', 'Beauté')], default='accessoires', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
